server:
  port: 8895
  session:
    timeout: 259200s

spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        generate_statistics: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oog-osu
    username: oog-osu
    password: oog-osu

swagger:
  enabled: true

flyway:
  enabled: true