server:
  port: 8895
  session:
    timeout: 259200s

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oog-osu
    username: oog-osu
    password: oog-osu

swagger:
  enabled: true