create table appeal
(
    id            int8 generated by default as identity,
    answer        text,
    answer_date   timestamp,
    creation_date timestamp,
    decision      varchar(255),
    due_date      timestamp,
    is_prolonged  boolean,
    question      text,
    state         varchar(255),
    citizen_id    int8,
    department_id int8,
    executor_id   int8,
    topic_id      int8,
    archived      bool,
    difficulty    varchar(255),
    return_reason text,
    is_complaint  bool,
    is_returned   bool,
    primary key (id)
);
create table citizen
(
    id          int8 generated by default as identity,
    address     varchar(255),
    email       varchar(255),
    first_name  varchar(255),
    last_name   varchar(255),
    middle_name varchar(255),
    phone       varchar(255),
    archived    bool,
    primary key (id)
);
create table d_department
(
    id      int8 generated by default as identity,
    name    varchar(255),
    archived      bool,
    primary key (id)
);
create table d_employee
(
    id            int8 generated by default as identity,
    email         varchar(255),
    first_name    varchar(255),
    last_name     varchar(255),
    middle_name   varchar(255),
    phone         varchar(255),
    qualification varchar(255),
    username      varchar(255),
    department_id int8,
    archived      bool,
    primary key (id)
);
create table d_topic
(
    id            int8 generated by default as identity,
    name          varchar(255),
    department_id int8,
    archived      bool,
    primary key (id)
);
create table principal
(
    username varchar(255) not null,
    password varchar(255),
    role     varchar(255),
    primary key (username)
);
alter table if exists appeal
    add constraint fk$appeal$citizen foreign key (citizen_id) references citizen;
alter table if exists appeal
    add constraint fk$appeal$department foreign key (department_id) references d_department;
alter table if exists appeal
    add constraint fk$appeal$executor foreign key (executor_id) references d_employee;
alter table if exists appeal
    add constraint fk$appeal$topic foreign key (topic_id) references d_topic;
alter table if exists d_employee
    add constraint fk$employee$department foreign key (department_id) references d_department;
alter table if exists d_topic
    add constraint fk$topic$department foreign key (department_id) references d_department;